Added Issue labeler work flow
rohitinu6/Stock-Price-Prediction pull request #166
Opened 2024-10-22 16:51 UTC by ygowthamr

## Description:  
This PR adds a GitHub Action to automate labeling of issues on creation or edit.  
The labels added are `gssoc-extd` (green), `hacktoberfest` (orange), and `level?` (purple).  
`level?` serves as a placeholder until the project admin assigns the final level during PR review.  
The workflow uses the GitHub API to ensure labels are updated with correct colors and descriptions

Fix #156 

@rohitinu6
Pls add labels like level3,gssoc-extd,hacktoberfest-accepted.

2024-10-22 17:46 UTC, jvedsaqib commented
@ygowthamr can you share a snapshot of the workflow

2024-10-22 18:36 UTC, jvedsaqib requested changes
@ygowthamr check proper color codes

2024-10-23 00:51 UTC, ygowthamr commented
@rohitinu6 
I have updated the code pls check and merge it

2024-10-23 04:54 UTC, Mayureshd-18 requested changes
@ygowthamr In the PR description please add an tested issue screenshot from your forked repo.
Thanks

2024-10-23 05:37 UTC, ygowthamr commented
@Mayureshd-18 
**The below are the images that you asked:**
- ![image](https://github.com/user-attachments/assets/a94c9ae0-bc90-4177-8797-e37f544aff09)
- ![image](https://github.com/user-attachments/assets/19b27d97-f391-497a-9d56-b5154321601d)

2024-10-23 05:53 UTC, Mayureshd-18 requested changes
@ygowthamr Please include all the labels:
1. gssoc-ext
2. hacktoberfest
3. hacktoberfest-accepted
2. level?

And also update the images after making these changes.
Thanks

2024-10-23 05:54 UTC, Mayureshd-18 commented
> @Mayureshd-18 @jvedsaqib **The below are the images that you asked:**
> 
> * ![image](https://private-user-images.githubusercontent.com/68599050/379117000-a94c9ae0-bc90-4177-8797-e37f544aff09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjMxMDEsIm5iZiI6MTcyOTY2MjgwMSwicGF0aCI6Ii82ODU5OTA1MC8zNzkxMTcwMDAtYTk0YzlhZTAtYmM5MC00MTc3LTg3OTctZTM3ZjU0NGFmZjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA1NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOGE4ZDJmNWVlMmQ1MjIwOGQ2ODgzMzE5MGQ3MGMxNTAyNDhjZTY5NjYzN2MyMTczNGIxMDZlNjNiMjViN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r3YFCA-ImXCXnBB8Gx9Jrnl9x45iTJhIaZDhb2wes48)
> * ![image](https://private-user-images.githubusercontent.com/68599050/379117010-19b27d97-f391-497a-9d56-b5154321601d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjMxMDEsIm5iZiI6MTcyOTY2MjgwMSwicGF0aCI6Ii82ODU5OTA1MC8zNzkxMTcwMTAtMTliMjdkOTctZjM5MS00OTdhLTlkNTYtYjUxNTQzMjE2MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA1NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzM1YWJhYzVmZjFhYTA3ZTZlYWI5MTg4NDkzMmIxYjdkYzA3YjhhNzM5ZTBhYzE2YmUwZWU5MTgxYTc4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j4jDx3FF3oTTjgJ_WemSiSxwnC0dCIXNMiwnOx5zhE0)
> 
> **Note :**
> 
> * In the above there is hacktoberfest label but i have updated in this commit, now this label will come as hacktoberfest-accepted
> 
> Pls merge my pr asap and try to give me at least level2 for this PR

The level 2 and 3 are reserved for new algos written from scratch. Thanks for understanding!

2024-10-23 05:58 UTC, ygowthamr commented
@Mayureshd-18 
Added all required things. Merge my pr

2024-10-23 05:59 UTC, Mayureshd-18 commented
> @Mayureshd-18 Added all required things. Merge my pr

Please add the tested image in the PR description itself.
Thanks

2024-10-23 06:05 UTC, ygowthamr commented
@Mayureshd-18 
**The below are the images after changing:**
- ![image](https://github.com/user-attachments/assets/c3e023b0-a016-44d5-a185-d4d674589959)

2024-10-23 06:21 UTC, Mayureshd-18 approved these changes
Looks good to me!

2024-10-23 06:22 UTC, Mayureshd-18 commented
> @ygowthamr check proper color codes

@jvedsaqib Please review this once.

2024-10-23 06:27 UTC, ygowthamr commented
@jvedsaqib 
Can you send me color codes so that i will update it.

2024-10-23 13:07 UTC, jvedsaqib commented
> @jvedsaqib Can you send me color codes so that i will update it.

gssoc-ext #0E4075
hacktoberfest #006b75
hacktoberfest-accepted #95D2AA
level1 #51635E
level2 #C03B25
level3 #7B6B8B

2024-10-23 13:16 UTC, ygowthamr commented
@jvedsaqib 
Updated pls check and merge my PR

2024-10-23 13:29 UTC, ygowthamr commented
@jvedsaqib @rohitinu6 
I think it should be fine kindly merge my PR

2024-10-23 17:33 UTC, jvedsaqib approved these changes

2024-10-23 17:40 UTC, ygowthamr commented
@rohitinu6 
Pls review and merge my PR

2024-10-24 03:55 UTC, ygowthamr commented
@rohitinu6 
Can you review and merge my PR

2024-10-24 04:37 UTC, Mayureshd-18 approved these changes
Changes look good to me!

2024-10-24 07:52 UTC, ygowthamr commented
@jvedsaqib @Mayureshd-18 @rohitinu6 
Everyone approved the changes pls merge it.please don't prolong it

2024-10-24 13:50 UTC, ygowthamr commented
@Mayureshd-18 @jvedsaqib @rohitinu6 
Anyone please merge my pr as everyone approved this PR

2024-10-25 02:00 UTC, rohitinu6 approved these changes

2024-10-25 02:00 UTC, merged