Removed deprecation warnings of input_length argument and HDF5 format of model saving
rohitinu6/Stock-Price-Prediction pull request #197
Opened 2024-10-27 14:11 UTC by shristirwt

Issue Reference: #193 

Description of changes: I updated the code to remove deprecation warnings of input_length argument and HDF5 format of model saving

2024-10-27 18:03 UTC, Mayureshd-18 requested changes
Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

2024-10-27 18:10 UTC, shristirwt commented
I have made the changes

2024-10-28 14:23 UTC, jvedsaqib approved these changes

2024-10-28 17:27 UTC, Mayureshd-18 approved these changes

2024-10-28 17:31 UTC, merged